### ISSUE TITLE
callback ngk bisa.

### ISSUE THREAD

**Issue by lordmen99** [JuniYadi/xendit-whmcs-unofficial#1]
halo mas bro, saya sudah coba dan install di whmcs saya, order masuk dan complete, tapi call back ngk jalan. saya sudah add url callback di xendit dashboard juga, waktu save&test callback error yg di invoice. kalo di Virtual account bisa

**Comment by JuniYadi** [comment]
Ini hanya utk XenInvoice ya. Bukan yg lain. Utk callback, silahkan hubungi pihak xendit jika ada kendala pada layanan mereka.
